config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#test'
  match 'retrieve-location/', to: 'posts#ajax_geolocation', via: 'post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  def self.search(search)
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
    @meeting = Meeting.new 
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.date_options = meeting_params[:date_options].first.split

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, date_options: [], location_options: [])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search])
    else
      @posts = Post.all
    end
  end

  def test

  end

  def ajax_geolocation
    @posts = Post.all
    respond_to do |format|
      format.json  { render json: @posts, :status => :ok }
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def search
    if params[:search].present?
      @posts = Post.search(params[:search])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.id = Post.new(params[:id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:id, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(meeting) do |f| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date_options %>
    <%= f.text_field :date_options %>
  </div>

  <div class="field">
    <%= f.label :location_options %>
    <%= f.text_field :location_options %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>


<%= simple_form_for @meeting do |f| %>
  <div class="meeting_option">
    <%= f.input :date_options, as: :array, placeholder: "date_options" %>
  </div>
  <div class="meeting_option">
    <%= f.input :location_options, as: :array, placeholder: "location_options" %>
  </div>
  <div class="submit-btn">
    <%= f.submit "Envoyez-nous vos disponibilités !", class: "btn" %>
  </div>
<% end %>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Date options:</strong>
  <%= @meeting.date_options %>
</p>

<p>
  <strong>Location options:</strong>
  <%= @meeting.location_options %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<div class="search-bar is-desktop">
  <form id="search_form">
      <%= form_tag search_courses_path, method: :get, class: "custom-input" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search By Keyword" %>
      <% end %>
      <%= submit_tag "Search", name: nil, form: "search_form", class: "search-btn" %>
   </form>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

I did this way using a form_tag and a text_field_tag, in addition the check for `params[:search]` in the controller. 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/test.html.erb
<p>bla</p>

<a href="#" id="click">click me</a>

<script>
  var pos = { lat: 43.12312, lng: 13.123123 };
  // $('#click').click(function(e) {
    // e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '/retrieve-location/',
      data: {coordinates: { lat: pos.lat, lng: pos.lng}},
      dataType: "script",
      success: function(data,status,xhr){
        console.log('There you go: ' + data);
        console.log('Success');
        $(document).append('There you go: ' + data);
      },
      error: function(xhr,status,error){
        console.log(xhr);
        console.log('Somethings gone wrong');
      }
    });
  // })
</script>